"""
dashboard.py - Interactive Dashboard

Displays the results of Bob's analysis using Dash/Plotly.
Reads pre-computed output files generated by the analysis pipeline.

Usage:
    python dashboard.py
    Then open http://127.0.0.1:8050 in your browser.

Prerequisites:
    Run 'make pipeline' first to generate the output files.
"""

import os

import dash
from dash import dcc, html, dash_table, Input, Output
import plotly.express as px
import pandas as pd

OUTPUT_DIR = "output"


def load_overview_data():
    """Load Part 2 data overview from CSV."""
    return pd.read_csv(os.path.join(OUTPUT_DIR, "part2_data_overview.csv"))


def load_statistical_data():
    """Load Part 3 frequency data from CSV."""
    return pd.read_csv(os.path.join(OUTPUT_DIR, "part3_frequencies.csv"))


def load_stats_results():
    """Load Part 3 statistical test results from CSV."""
    return pd.read_csv(os.path.join(OUTPUT_DIR, "part3_stats_results.csv"))


def load_subset_data():
    """Load Part 4 subset analysis from CSV."""
    return pd.read_csv(os.path.join(OUTPUT_DIR, "part4_subset_analysis.csv"))


# Initialize the Dash app
app = dash.Dash(__name__, suppress_callback_exceptions=True)
app.title = "Teiko Bio - Cell Population Analysis"

# App layout
app.layout = html.Div([
    html.H1("Teiko Bio - Immune Cell Population Analysis",
            style={"textAlign": "center", "color": "#2c3e50", "marginBottom": "10px"}),
    html.P("Clinical trial data analysis for miraclib drug candidate",
           style={"textAlign": "center", "color": "#7f8c8d", "marginBottom": "30px"}),

    dcc.Tabs(id="tabs", value="tab-overview", children=[
        dcc.Tab(label="Part 2: Data Overview", value="tab-overview"),
        dcc.Tab(label="Part 3: Statistical Analysis", value="tab-stats"),
        dcc.Tab(label="Part 4: Subset Analysis", value="tab-subset"),
    ]),

    html.Div(id="tab-content", style={"padding": "20px"})
])


@app.callback(Output("tab-content", "children"), Input("tabs", "value"))
def render_tab(tab):
    if tab == "tab-overview":
        return render_overview_tab()
    elif tab == "tab-stats":
        return render_stats_tab()
    elif tab == "tab-subset":
        return render_subset_tab()


def render_overview_tab():
    """Render Part 2: Data Overview."""
    df = load_overview_data()

    # Summary statistics
    sample_count = df["sample"].nunique()
    populations = df["population"].unique().tolist()

    # Average percentages per population
    avg_pct = df.groupby("population")["percentage"].mean().reset_index()
    avg_pct.columns = ["population", "avg_percentage"]

    fig_bar = px.bar(
        avg_pct,
        x="population",
        y="avg_percentage",
        title="Average Relative Frequency by Cell Population (All Samples)",
        labels={"avg_percentage": "Average Relative Frequency (%)", "population": "Cell Population"},
        color="population"
    )

    # Show a sample of the data table
    sample_df = df.head(50)

    return html.Div([
        html.H3("Data Overview - Relative Frequencies"),
        html.P(f"Total samples: {sample_count} | Populations: {', '.join(populations)}"),

        dcc.Graph(figure=fig_bar),

        html.H4("Sample Data (first 50 rows)"),
        dash_table.DataTable(
            data=sample_df.to_dict("records"),
            columns=[{"name": c, "id": c} for c in sample_df.columns],
            page_size=15,
            style_table={"overflowX": "auto"},
            style_cell={"textAlign": "left", "padding": "8px"},
            style_header={"backgroundColor": "#2c3e50", "color": "white", "fontWeight": "bold"},
            filter_action="native",
            sort_action="native",
        )
    ])


def render_stats_tab():
    """Render Part 3: Statistical Analysis."""
    df = load_statistical_data()
    stats_df = load_stats_results()

    # Boxplot: responders vs non-responders
    df["response_label"] = df["response"].map({"yes": "Responders", "no": "Non-Responders"})

    fig_box = px.box(
        df,
        x="population",
        y="percentage",
        color="response_label",
        title="Cell Population Relative Frequencies: Responders vs Non-Responders<br>(Melanoma, Miraclib, PBMC)",
        labels={
            "percentage": "Relative Frequency (%)",
            "population": "Cell Population",
            "response_label": "Response"
        },
        color_discrete_map={"Responders": "#4ECDC4", "Non-Responders": "#FF6B6B"}
    )

    # Format stats table for display
    display_stats = stats_df.rename(columns={
        "population": "Population",
        "u_statistic": "U-Statistic",
        "p_value": "p-value",
        "significant": "Significant (p<0.05)",
        "n_responders": "N Responders",
        "n_non_responders": "N Non-Responders"
    })

    stats_html = [
        html.H4("Mann-Whitney U Test Results"),
        dash_table.DataTable(
            data=display_stats.to_dict("records"),
            columns=[{"name": c, "id": c} for c in display_stats.columns],
            style_cell={"textAlign": "center", "padding": "8px"},
            style_header={"backgroundColor": "#2c3e50", "color": "white", "fontWeight": "bold"},
            style_data_conditional=[
                {"if": {"filter_query": '{Significant (p<0.05)} = "Yes"'},
                 "backgroundColor": "#d4edda", "color": "#155724"}
            ]
        )
    ]

    return html.Div([
        html.H3("Statistical Analysis - Responders vs Non-Responders"),
        html.P("Comparing cell population relative frequencies between responders and "
               "non-responders among melanoma patients receiving miraclib (PBMC samples only)."),
        dcc.Graph(figure=fig_box),
        *stats_html
    ])


def render_subset_tab():
    """Render Part 4: Subset Analysis."""
    df = load_subset_data()

    # Parse the category-based CSV into separate dataframes
    project_df = df[df["category"] == "project"][["group", "count"]].copy()
    project_df.columns = ["Project", "Sample Count"]

    response_df = df[df["category"] == "response"][["group", "count"]].copy()
    response_df.columns = ["Response", "Subject Count"]
    response_df["Response"] = response_df["Response"].map(
        {"responders": "Responders", "non_responders": "Non-Responders"}
    )

    sex_df = df[df["category"] == "sex"][["group", "count"]].copy()
    sex_df.columns = ["Sex", "Subject Count"]
    sex_df["Sex"] = sex_df["Sex"].map({"male": "Male", "female": "Female"})

    total_samples = project_df["Sample Count"].sum()

    fig_project = px.bar(
        project_df,
        x="Project",
        y="Sample Count",
        title="Samples by Project (Melanoma, PBMC, Baseline, Miraclib)",
        color="Project"
    )

    fig_response = px.pie(
        response_df,
        values="Subject Count",
        names="Response",
        title="Responders vs Non-Responders (Unique Subjects)",
        color_discrete_map={"Responders": "#4ECDC4", "Non-Responders": "#FF6B6B"}
    )

    fig_sex = px.pie(
        sex_df,
        values="Subject Count",
        names="Sex",
        title="Male vs Female (Unique Subjects)",
        color_discrete_map={"Male": "#3498db", "Female": "#e74c3c"}
    )

    return html.Div([
        html.H3("Subset Analysis - Melanoma Baseline Miraclib PBMC"),
        html.P(f"Total matching samples: {total_samples}"),

        html.Div([
            html.Div([dcc.Graph(figure=fig_project)], style={"width": "100%"}),
        ]),

        html.Div([
            html.Div([dcc.Graph(figure=fig_response)], style={"width": "50%", "display": "inline-block"}),
            html.Div([dcc.Graph(figure=fig_sex)], style={"width": "50%", "display": "inline-block"}),
        ]),

        html.H4("Summary Data"),
        dash_table.DataTable(
            data=df.to_dict("records"),
            columns=[{"name": c, "id": c} for c in df.columns],
            style_table={"overflowX": "auto"},
            style_cell={"textAlign": "left", "padding": "8px"},
            style_header={"backgroundColor": "#2c3e50", "color": "white", "fontWeight": "bold"},
        )
    ])


if __name__ == "__main__":
    # Check that output files exist
    required_files = [
        "part2_data_overview.csv",
        "part3_frequencies.csv",
        "part3_stats_results.csv",
        "part4_subset_analysis.csv"
    ]
    missing = [f for f in required_files if not os.path.exists(os.path.join(OUTPUT_DIR, f))]
    if missing:
        print(f"ERROR: Missing output files: {missing}")
        print("Please run 'make pipeline' first to generate the analysis outputs.")
        exit(1)

    print("Starting dashboard at http://127.0.0.1:8050")
    app.run_server(debug=True, host="0.0.0.0", port=8050)
